# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_posts', to='blogit.Tag', verbose_name='Tags'),
        ),
    ]
